const form=document.querySelector('#atlasForm'),input=document.querySelector('#atlasInput'),messages=document.querySelector('#atlasMessages'),tickets=document.querySelector('#ticketList'),ticketCount=document.querySelector('#openCount'),handoff=document.querySelector('#handoffButton');
const intents=[
 {match:/price|cost|plan|subscription|billing/i,reply:'Our sample plans start at $29 per month. A person can help match a plan to your needs.',tag:'Billing'},
 {match:/hour|open|close|time|weekend/i,reply:'Sample support hours are Monday to Friday, 9 AM–6 PM Eastern. The team can confirm holiday hours.',tag:'Hours'},
 {match:/refund|cancel|return/i,reply:'Refund requests need a team review. Share an order number and support can check the policy for you.',tag:'Refund'},
 {match:/human|person|agent|team|contact|help/i,reply:'I can create a support request so a team member can follow up. This demo does not send a real ticket.',tag:'Handoff'}
];
let ticketId=1048;
function addMessage(text,who='assistant'){const item=document.createElement('div');item.className=`chat-message ${who}`;item.innerHTML=who==='assistant'?`<span class="message-avatar">A</span><p>${text}</p>`:`<p></p>`;if(who!=='assistant')item.querySelector('p').textContent=text;messages.append(item);messages.scrollTop=messages.scrollHeight}
function addTicket(reason){ticketId++;const item=document.createElement('button');item.className='ticket-row selected';item.dataset.status='open';item.innerHTML=`<span class="ticket-priority"></span><span class="ticket-copy"><b>New request · #${ticketId}</b><small>${reason} · just now</small></span><span class="ticket-state">OPEN</span>`;item.addEventListener('click',()=>{document.querySelectorAll('.ticket-row').forEach(t=>t.classList.remove('selected'));item.classList.add('selected')});tickets.prepend(item);ticketCount.textContent=String(Number(ticketCount.textContent)+1);document.querySelector('#ticketToast').textContent=`Sample ticket #${ticketId} added to the inbox.`;setTimeout(()=>document.querySelector('#ticketToast').textContent='',3200)}
function respond(value){const clean=value.trim();if(!clean)return;addMessage(clean,'customer');input.value='';const intent=intents.find(x=>x.match.test(clean));const result=intent?.reply??'I don’t have a verified answer for that yet. I can pass it to a support teammate for review.';window.setTimeout(()=>{addMessage(result);if(/team member|support request|pass it/i.test(result))addTicket(intent?.tag??'Needs review')},280)}
form.addEventListener('submit',e=>{e.preventDefault();respond(input.value)});document.querySelectorAll('[data-sample-question]').forEach(b=>b.addEventListener('click',()=>respond(b.dataset.sampleQuestion)));handoff.addEventListener('click',()=>addTicket('Requested person'));
document.querySelector('#resolveTicket').addEventListener('click',()=>{const row=tickets.querySelector('.ticket-row.selected');if(!row)return;row.dataset.status='resolved';row.querySelector('.ticket-state').textContent='DONE';row.classList.add('resolved');ticketCount.textContent=String(Math.max(0,Number(ticketCount.textContent)-1));document.querySelector('#ticketToast').textContent='Sample ticket marked resolved.';setTimeout(()=>document.querySelector('#ticketToast').textContent='',2500)});
